# Generated by Django 5.2.5 on 2025-09-14 15:13

import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='last_update',
            field=django_jalali.db.models.jDateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'در انتظار پرداخت'), ('processing', 'در حال آماده سازی سفارش'), ('on the way', 'تحویل پیک موتوری داده شد'), ('delivered', 'تحویل مشتری داده شد')], default='pending'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_ordered',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True),
        ),
    ]
