# Generated by Django 5.2.5 on 2025-09-14 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payment', '0002_order_last_update_order_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'در انتظار پرداخت'), ('Processing', 'در حال آماده سازی سفارش'), ('On The Way', 'تحویل پیک موتوری داده شد'), ('Delivered', 'تحویل مشتری داده شد')], default='Pending'),
        ),
    ]
