# Generated by Django 5.2.5 on 2025-09-15 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payment', '0003_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'در انتظار پرداخت'), ('Processing', 'در حال آماده سازی سفارش'), ('On The Way', 'تحویل پیک موتوری داده شد'), ('Delivered', 'تحویل مشتری داده شد'), ('canceled', 'سفارش لغو شده است')], default='Pending'),
        ),
    ]
