# Generated by Django 5.2.5 on 2025-08-22 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StaffRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Waiter', 'گارسون'), ('Chef', 'سرآشپز'), ("Chef's Assistant", 'کمک آشپز'), ('Cashier', 'صندوق دار'), ('Delivery Guy', 'پیک')], default='Waiter')),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('picture', models.ImageField(upload_to='upload/staff/')),
                ('bio', models.TextField(blank=True, max_length=150000, null=True)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainPage.staffrole')),
            ],
        ),
    ]
