# Generated by Django 5.2.5 on 2025-08-22 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainPage', '0002_staff_email_staff_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffrole',
            name='name',
            field=models.CharField(choices=[('Manager', 'مدیر'), ('Waiter', 'گارسون'), ('Chef', 'سرآشپز'), ("Chef's Assistant", 'کمک آشپز'), ('Cashier', 'صندوق دار'), ('Delivery Guy', 'پیک')], default='Waiter'),
        ),
    ]
