# Generated by Django 5.2.5 on 2025-08-22 12:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainPage', '0003_alter_staffrole_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='birth',
            field=models.IntegerField(default=1960, validators=[django.core.validators.MinValueValidator(1960), django.core.validators.MaxValueValidator(2007)]),
        ),
        migrations.AddField(
            model_name='staff',
            name='country',
            field=models.CharField(default='IRAN', max_length=50),
        ),
    ]
