# Generated by Django 5.2.5 on 2025-08-22 12:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainPage', '0004_staff_birth_staff_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='birth',
            field=models.IntegerField(default=1960, validators=[django.core.validators.MinValueValidator(1960), django.core.validators.MaxValueValidator(2025)]),
        ),
    ]
