# Generated by Django 5.2.5 on 2025-09-11 07:20

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainPage', '0008_remove_deliveryinfouser_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DeliveryInfoUser',
            new_name='DeliveryInfoProfile',
        ),
        migrations.RenameField(
            model_name='deliveryinfoprofile',
            old_name='username',
            new_name='user',
        ),
    ]
