# Generated by Django 5.2.5 on 2025-09-11 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainPage', '0009_rename_deliveryinfouser_deliveryinfoprofile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryinfoprofile',
            name='address',
            field=models.TextField(blank=True, max_length=400),
        ),
    ]
