# Generated by Django 5.2.5 on 2025-09-12 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainPage', '0010_alter_deliveryinfoprofile_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryinfoprofile',
            name='shopping_cart',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
